# TODO
# Only run setup.sql if on a "fresh" database


---
version: "3.9"  # optional since v1.27.0
services:
  settler:
    build:
      context: .
      target: settler
    env_file:
      - ./envs/settler.env
    environment:
      - PORT=8082
      - CACHEADDRESS=http://cache:8081/balance
    networks:
      - mynet
    depends_on:
      - cache
  processor_0:
    build:
      context: .
      target: processor
    env_file:
      - ./envs/postgres.env
      - ./envs/processor.env
    environment:
      - DBHOST=db
      - PORT=8083
      - CACHEADDRESS=http://cache:8081/balance
    networks:
      - mynet
    depends_on:
      - cache
  processor_1:
    build:
      context: .
      target: processor
    env_file:
      - ./envs/postgres.env
      - ./envs/processor.env
    environment:
      - DBHOST=db
      - PORT=8084
      - CACHEADDRESS=http://cache:8081/balance
    networks:
      - mynet
    depends_on:
      - cache
  cache:
    build:
      context: .
      target: cache
    environment:
      - DBHOST=db
    depends_on:
      - db
    networks:
      - mynet
  balancer:
    build:
      context: .
      target: balancer
    ports:
      # default namespace : container namespace
      - "8080:8080"
    environment:
      - NODEADDRESS0=http://processor:8083
      - NODEADDRESS1=http://processor:8084
    env_file:
      - ./envs/balancer.env
    networks:
      - mynet
    depends_on:
      - processor_0
      - processor_1
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./dbinit/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: polkapass
      POSTGRES_DB: payments
      POSTGRES_USER: polka
    networks:
      - mynet

volumes:
  dbinit:
  pgdata:
networks:
  mynet:
